#include <jni.h>
#include <stdio.h>
#include "qube_logutils.h"
#include <dlfcn.h>
#include <fcntl.h>
#include <errno.h>
#include <malloc.h>
#include <signal.h>
#include <stdlib.h>
#include <unistd.h>
#include <dlfcn.h>
#include <unwind.h>
#include <dlfcn.h>
#include <sys/stat.h>
#include "qube_compat_qemu.h"
#include "qube_compat.h"
#include <errno.h>
