#!/usr/bin/env python3
# Copyright (C) Rhn 2026
# Regenerates UnicodeKeysyms.java, the unicode to legacy X11 keysym table used by KeySymMap.
# Usage: python3 tools/gen-unicode.py (qemu version)
import argparse
import os
import re
import urllib.error
import urllib.request

XKB_URL = "https://raw.githubusercontent.com/xkbcommon/libxkbcommon/master/include/xkbcommon/xkbcommon-keysyms.h"
QEMU_URL = "https://raw.githubusercontent.com/qemu/qemu/v%s/ui/vnc_keysym.h"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "qube-android-lib", "src", "main",
                   "java", "com", "max2idea", "android", "qube", "keyboard", "UnicodeKeysyms.java")

TEMPLATE = """/*
Copyright (C) Rhn 2026
 */
package com.max2idea.android.qube.keyboard;

import java.util.Arrays;

// XXX: generated by tools/gen-unicode.py from xkbcommon keysyms
// limited to the ones qemu knows, run it again if qemu adds names
final class UnicodeKeysyms {

    // sorted for the binary search
    private static final int[] CODEPOINTS = {
%s
    };

    // same order as CODEPOINTS
    private static final int[] KEYSYMS = {
%s
    };

    private UnicodeKeysyms() {
    }

    // the codepoint itself when the keymaps use the U+XXXX name
    static int get(int codepoint) {
        int index = Arrays.binarySearch(CODEPOINTS, codepoint);
        return index >= 0 ? KEYSYMS[index] : codepoint;
    }
}
"""


def fetch(url):
    try:
        return urllib.request.urlopen(url, timeout=30).read().decode("utf-8")
    except urllib.error.HTTPError as e:
        raise SystemExit("%s returned %d" % (url, e.code))


def qemu_keysyms(versions):
    # every keysym value the given qemu versions can name in a keymap
    values = set()
    for version in versions:
        for line in fetch(QEMU_URL % version).splitlines():
            m = re.match(r'\{\s*"[^"]+",\s*0x([0-9a-fA-F]+)\}', line)
            if m:
                values.add(int(m.group(1), 16))
    return values


def pairs(known):
    # unicode codepoint to legacy keysym, Latin-1 and identical values need no entry
    table = {}
    for line in fetch(XKB_URL).splitlines():
        m = re.match(r"#define XKB_KEY_\w+\s+0x([0-9a-fA-F]+)\s+/\* U\+([0-9A-F]+) ", line)
        if not m:
            continue
        keysym, codepoint = int(m.group(1), 16), int(m.group(2), 16)
        if codepoint < 0x100 or keysym == codepoint or keysym >= 0xFE00 or keysym not in known:
            continue
        table.setdefault(codepoint, keysym)
    return sorted(table.items())


def rows(values):
    lines, line = [], "       "
    for value in values:
        token = " 0x%04X," % value
        if len(line) + len(token) > 100:
            lines.append(line)
            line = "       "
        line += token
    lines.append(line)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate UnicodeKeysyms.java")
    parser.add_argument("versions", nargs="+", help="qemu versions such as 11.1.2")
    table = pairs(qemu_keysyms(parser.parse_args().versions))
    with open(OUT, "w") as f:
        f.write(TEMPLATE % (rows([c for c, _ in table]), rows([k for _, k in table])))
    print("%d entries written to %s" % (len(table), os.path.normpath(OUT)))


if __name__ == "__main__":
    main()
