/*
Copyright (C) Max Kastanas 2012
Copyright (C) Rhn 2026
 */
package com.max2idea.android.qube.machine;

public enum MachineProperty {
    MACHINE_NAME, SNAPSHOT_NAME,
    STATUS, LAST_UPDATED,
    UI, MOUSE, ENABLE_USBMOUSE, KEYBOARD,
    ARCH, MACHINETYPE, CPU, CPUNUM, MEMORY, ENABLE_MTTCG, ENABLE_KVM, ENABLE_VENUS, PRIO,
    DISABLE_ACPI, DISABLE_HPET, DISABLE_TSC, DISABLE_FD_BOOT_CHK,
    HDA, HDB, HDC, HDD, SHARED_FOLDER, SHARED_FOLDER_MODE, SHARED_FOLDER_TYPE, HDCONFIG,
    CDROM, FDA, FDB, SD,
    MEDIA_INTERFACE, HDA_INTERFACE, HDB_INTERFACE, HDC_INTERFACE, HDD_INTERFACE, CDROM_INTERFACE,
    BOOT_CONFIG, BIOS, BIOS_TYPE, BIOS_CODE, BIOS_VARS, TCG_BUFFER, KERNEL, INITRD, APPEND,
    VGA, SOUNDCARD, NETCONFIG, HOSTFWD, GUESTFWD, NICCONFIG, DNS,
    NON_REMOVABLE_DRIVE, REMOVABLE_DRIVE, DRIVE_ENABLED,
    EXTRA_PARAMS, OTHER
}

